# Generated by Django 4.2 on 2024-06-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Id пользователя (В боте написать /start)')),
            ],
            options={
                'verbose_name': 'Пользователи в бот заказов',
                'verbose_name_plural': 'Пользователи в бот заказов',
            },
        ),
        migrations.CreateModel(
            name='WorkUserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='')),
            ],
            options={
                'verbose_name': 'Для бота разработчиков',
                'verbose_name_plural': 'Для бота разработчиков',
            },
        ),
    ]
